<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="24" started-at="2017-01-23T21:33:09Z" finished-at="2017-01-23T21:33:09Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="24" started-at="2017-01-23T21:33:09Z" finished-at="2017-01-23T21:33:09Z">
      <class name="TestNG_Parameters">
        <test-method status="FAIL" signature="testFromfill(java.lang.String, java.lang.String, java.lang.Integer)[pri:0, instance:TestNG_Parameters@6a2bcfcb]" name="testFromfill" duration-ms="0" started-at="2017-01-23T16:33:09Z" data-provider="gerData" finished-at="2017-01-23T16:33:09Z">
          <exception class="org.testng.TestNGException">
            <message>
              <![CDATA[
Method public void TestNG_Parameters.testFromfill(java.lang.String,java.lang.String,java.lang.Integer) requires a @DataProvider named : gerData]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestNGException: 
Method public void TestNG_Parameters.testFromfill(java.lang.String,java.lang.String,java.lang.Integer) requires a @DataProvider named : gerData
	at org.testng.internal.Parameters.findDataProvider(Parameters.java:336)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:498)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1293)
	at org.testng.internal.Invoker.createParameters(Invoker.java:1020)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1110)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestNGException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testFromfill -->
      </class> <!-- TestNG_Parameters -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
